# Generated by Django 3.0.5 on 2020-04-26 14:21

import customers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Surname')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=customers.models.get_customer_photo_upload_to, verbose_name='Photo')),
                ('phone', models.CharField(default='', max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(default='', max_length=150, verbose_name='Email')),
                ('country', models.CharField(default='', max_length=50, verbose_name='Country')),
                ('postal_code', models.CharField(default='', max_length=15, verbose_name='Postal Code')),
                ('region', models.CharField(default='', max_length=100, verbose_name='Region')),
                ('locality', models.CharField(default='', max_length=100, verbose_name='Locality')),
                ('address', models.CharField(default='', max_length=200, verbose_name='Address')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fields_changed', jsonfield.fields.JSONField(null=True)),
                ('log_type', models.CharField(choices=[('creation', 'Creation'), ('edition', 'Edition'), ('deletion', 'Deletion')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
